# Generated by Django 4.2 on 2023-04-11 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 46, 37, 266813))),
                ('data_atualizacao', models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 46, 37, 266844))),
            ],
        ),
    ]
