# Generated by Django 4.2 on 2023-04-11 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 46, 44, 840593)),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 46, 44, 840563)),
        ),
    ]
