# Generated by Django 4.2 on 2023-04-11 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 47, 1, 386251)),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 47, 1, 386220)),
        ),
    ]
