# Generated by Django 4.2 on 2023-04-11 23:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_data_atualizacao_and_more'),
        ('departamentos', '0003_alter_departamento_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('horas_necessarias', models.IntegerField()),
                ('horas_realizadas', models.IntegerField(default=0)),
                ('prazo_estimado', models.DateField(default=None)),
                ('ultimo_calculo_horas', models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 47, 1, 465581))),
                ('horas_supervisao', models.IntegerField()),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 47, 1, 465695))),
                ('data_atualizacao', models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 47, 1, 465725))),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioProjeto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('horas_trabalhadas', models.IntegerField()),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 47, 1, 467331))),
                ('data_atualizacao', models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 47, 1, 467371))),
                ('funcionario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('projeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto')),
            ],
        ),
    ]
