# Generated by Django 4.2 on 2023-04-12 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarioprojeto',
            old_name='funcionario_id',
            new_name='funcionario',
        ),
        migrations.RenameField(
            model_name='funcionarioprojeto',
            old_name='projeto_id',
            new_name='projeto',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='departamento_id',
            new_name='departamento',
        ),
        migrations.AlterField(
            model_name='funcionarioprojeto',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 21, 36, 16, 768645)),
        ),
        migrations.AlterField(
            model_name='funcionarioprojeto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 21, 36, 16, 768637)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 21, 36, 16, 768347)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 21, 36, 16, 768338)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ultimo_calculo_horas',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 21, 36, 16, 768314)),
        ),
    ]
