# Generated by Django 4.2 on 2023-04-12 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_rename_funcionario_id_funcionarioprojeto_funcionario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='supervisor_id',
            new_name='supervisor',
        ),
        migrations.AlterField(
            model_name='funcionarioprojeto',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 21, 36, 46, 271181)),
        ),
        migrations.AlterField(
            model_name='funcionarioprojeto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 21, 36, 46, 271172)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 21, 36, 46, 270834)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 21, 36, 46, 270828)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ultimo_calculo_horas',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 21, 36, 46, 270800)),
        ),
    ]
