# Generated by Django 4.2 on 2023-04-13 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_rename_supervisor_id_projeto_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarioprojeto',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 2, 23, 1, 273557)),
        ),
        migrations.AlterField(
            model_name='funcionarioprojeto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 2, 23, 1, 273549)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 2, 23, 1, 273259)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 2, 23, 1, 273250)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ultimo_calculo_horas',
            field=models.DateField(default=datetime.datetime(2023, 4, 13, 2, 23, 1, 273228)),
        ),
    ]
