# Generated by Django 4.2 on 2023-04-13 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_funcionarioprojeto_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarioprojeto',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 5, 34, 43, 977485)),
        ),
        migrations.AlterField(
            model_name='funcionarioprojeto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 5, 34, 43, 977477)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 5, 34, 43, 977187)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 5, 34, 43, 977176)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='prazo_estimado',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ultimo_calculo_horas',
            field=models.DateField(default=datetime.datetime(2023, 4, 13, 5, 34, 43, 977154)),
        ),
    ]
