# Generated by Django 4.2 on 2023-04-11 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 47, 1, 462964)),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 47, 1, 462925)),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 47, 1, 461246)),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 23, 47, 1, 461204)),
        ),
    ]
