# Generated by Django 4.2 on 2023-04-12 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='departamento_id',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='sexo_id',
            new_name='sexo',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 20, 9, 55, 893915)),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 20, 9, 55, 893904)),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 20, 9, 55, 893616)),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 20, 9, 55, 893600)),
        ),
    ]
