# Generated by Django 4.2 on 2023-04-12 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_rename_departamento_id_funcionario_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 20, 12, 19, 265454)),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 20, 12, 19, 265446)),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 20, 12, 19, 265137)),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 20, 12, 19, 265109)),
        ),
    ]
