# Generated by Django 4.2 on 2023-04-13 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 5, 34, 37, 305008)),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 5, 34, 37, 304999)),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 5, 34, 37, 304716)),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 5, 34, 37, 304701)),
        ),
    ]
